[tool.poetry]
name = "pytetra"
version = "0.1.0"
description = "tetra for M1 Mac"
authors = ["WeiChen Lin <asdfg09487@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
